name: nft-manager
services:
- name: web
  github:
    branch: master
    deploy_on_push: true
    repo: Ch3fC0d3/NFTManager
  build_command: npm install tailwindcss && npm run build
  run_command: npm run preview -- --host 0.0.0.0 --port ${PORT:-8080}
  environment_slug: node-js
  envs:
  - key: NODE_ENV
    value: production
  routes:
  - path: /
